version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password123!
      ACCEPT_EULA: Y
    ports:
      - 5555:1433
      - 5554:1434
    volumes:
      - sqlvolume:/var/opt/mssql
  gccdockerworkshop:
    image: gccdockerworkshopv1
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      ConnectionStrings__GCCDockerWorkshopDB: Data Source=mssql;User Id=sa;Password=Password123!
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5055:80
    depends_on:
      - mssql
volumes:
  sqlvolume:
    external: true
    name: mysqlbackup
  
